<a href="https://colab.research.google.com/github/jo-soobin/numpy-pandas/blob/master/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
# array 생성
arr_1 = np.arange(1000)

In [ ]:
type(arr_1)

numpy.ndarray

In [ ]:
arr_1

In [ ]:
# array 를 list로 변경 가능
arr2list = list(arr_1)

In [ ]:
type(arr2list)

list

In [ ]:
list_2 = [i for i in range(0,50)]

In [ ]:
arr_2 = np.array(list_2)

In [ ]:
type(arr_2)

numpy.ndarray

In [ ]:
list_3 = ["1", "2", "3"]

In [ ]:
arr_3 = np.array(list_3)

In [ ]:
arr_3

array(['1', '2', '3'], dtype='<U1')

In [ ]:
arr_2*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
# 문자가 섞여있으면 연산이 동작하지 않는다. 
arr_3+2

UFuncTypeError: ignored

In [ ]:
my_arr = np.arange(1000000)

In [ ]:
my_list = list(np.arange(1000000))

In [ ]:
%time for _ in range(100): my_arr2 = my_arr*2

CPU times: user 104 ms, sys: 9.99 ms, total: 114 ms
Wall time: 116 ms


In [ ]:
%time for _ in range(100): my_list2 = [ i*2 for i in my_list ]

CPU times: user 21.2 s, sys: 1.48 s, total: 22.6 s
Wall time: 22.9 s


In [ ]:

# m2 16 512 -> 200
# m1pro 16 512 -> 230

In [ ]:
# array 생성
data_1 = [6,7,8,9,2]

In [ ]:
type(data_1)

list

In [ ]:
arr_1 = np.array(data_1)

In [ ]:
arr_1.ndim

1

In [ ]:
data_2 = [1,2]

In [ ]:
arr_2 = np.array(data_2)

In [ ]:
arr_2#vector

array([1, 2])

In [ ]:
arr_2.ndim

1

In [ ]:
data_3 = [1,2,3]

In [ ]:
arr_3 = np.array(data_3)

In [ ]:
arr_3.ndim

1

In [ ]:
data_4 = [4,5,6]

In [ ]:
arr_4 = np.array(data_4)

In [ ]:
data_5 = [data_3, data_4]

In [ ]:
arr_5 = np.array(data_5)

In [ ]:
arr_5#matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_5.ndim

2

In [ ]:
data_6 = [[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]]

In [ ]:
arr_6 = np.array(data_6)

In [ ]:
arr_6.ndim

3

In [ ]:
arr_6

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# 참고
# np.mat 이라는 함수를 통해 matrix 를 생성할수 있지만 생성하지 않는다. 

In [ ]:
# 빈 리스트 = []
# 숫자 초기화 = 0 또는 1로 초기화
# np.random.randn # 추정이나 예측하기 위해서 초기값으로 지정할때 

In [ ]:
np.random.randn(1,5)

array([[-0.09891324,  1.96457828, -0.65821774, -0.93266402,  0.09961043]])

In [ ]:
np.random.randn(3,5)

array([[-0.09359006, -0.92660472, -1.42632909,  0.49077081,  0.30770944],
       [-1.30468568, -0.34691446,  1.7737476 , -0.11729096, -0.33714811],
       [ 0.46342275,  1.58187564, -1.55272664, -1.07910541,  2.13808451]])

In [ ]:
np.random.randn(3,5,6)

array([[[ 1.81946064, -0.09427805,  0.11148846,  0.94018138,
         -0.93928009,  0.94655672],
        [-0.80307792, -0.22713486,  0.28915325,  1.71146385,
         -1.12661058,  0.04841711],
        [-1.72744916, -1.01852592,  0.74616429,  0.22652579,
         -0.05351721,  1.52918561],
        [ 0.41315363, -1.55127071,  0.18117266, -0.40142457,
         -0.18166324, -0.10458889],
        [ 1.80138067, -0.15736433,  0.71089323, -1.32552522,
          1.57774828,  1.42143728]],

       [[ 1.19745332, -2.01504848,  0.6871091 ,  1.75057598,
         -1.55935626,  1.20665632],
        [-0.24772063, -0.17537527, -1.04310001,  0.94770618,
         -0.47306092, -0.49230868],
        [ 1.02468446,  2.58114683,  0.2320607 ,  0.71138204,
          0.02572049, -0.28086979],
        [ 0.72401734,  0.42836059,  0.57171749, -0.01509086,
         -0.42553183,  0.80471468],
        [-1.57823864, -0.22102428, -0.29232489, -0.57197782,
          0.25096409,  0.03849466]],

       [[ 1.74565978,  1.2

In [ ]:
arr_7 = np.zeros(10)

In [ ]:
arr_7

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr_8 = np.zeros((10,10))

In [ ]:
arr_8 # 10x10인 값이 0으로 채워진 행렬이 생성된다.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr_9 = np.zeros((10,10,3))

In [ ]:
arr_9

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
  

In [ ]:
arr_9.shape

(10, 10, 3)

In [ ]:
arr_7.shape

(10,)

In [ ]:
arr_6.shape

(2, 2, 3)

In [ ]:
arr_10 = np.empty((3,4))

In [ ]:
arr_11 = np.empty((3,5))

In [ ]:
arr_10

array([[4.67136618e-316, 0.00000000e+000, 7.92975362e-321,
        2.65179261e-316],
       [6.91196642e-310, 2.65179222e-316, 6.91196642e-310,
        6.91196642e-310],
       [0.00000000e+000, 9.88131292e-324, 2.38828544e-314,
        3.12237178e-120]])

In [ ]:
arr_11

array([[0.09359006, 0.92660472, 1.42632909, 0.49077081, 0.30770944],
       [1.30468568, 0.34691446, 1.7737476 , 0.11729096, 0.33714811],
       [0.46342275, 1.58187564, 1.55272664, 1.07910541, 2.13808451]])

In [ ]:
np.full((3,4), 0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.full((3,4), 1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.full((3,4), 2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
# numpy 배열의 산술 연산
# numpy 배열은 반복문을 작성하지 않고 데이터를 일괄 처리할수 있다.
# 이를 벡터화 기능이라고 한다.

In [ ]:
arr_1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
# 요소곱
arr_1 * arr_1

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
# 덧셈, 뺄셈
arr_1 + arr_1

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
# 나눗셈
arr_1/arr_1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 비교연산자 사용가능
arr_1 >= arr_1

array([[ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# 행렬곱 
arr_2 = np.array([[1,2,3],[4,5,6]])
arr_3 = np.array([[7,10],[8,11],[9,12]])

In [ ]:
np.dot(arr_2,arr_3) # 행렬 곱셈을 위한 연산dot

array([[ 50,  68],
       [122, 167]])

In [ ]:
# 색인과 슬라이싱
# 리스트와 동일

In [ ]:
arr_1 = np.arange(10)

In [ ]:
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_1[5]

5

In [ ]:
arr_1[5:8]

array([5, 6, 7])

In [ ]:
arr_1[-1:]

array([9])

In [ ]:
고객정보
이름 , 나이, 사는곳, 자산, 자가, 성별, 전화번호, .... , 상품 구매 여부 

In [ ]:
arr_1[-1:]

array([9])

In [ ]:
arr_1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])

In [ ]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
arr_1.shape

(5, 4)

In [ ]:
arr_1[:,-1]

array([ 4,  8, 12, 16, 20])

In [ ]:
arr_1[:,-1].shape

(5,)

In [ ]:
arr_1[:,-1:].shape

(5, 1)

In [ ]:
arr_2 = np.arange(24).reshape(3,2,4) 
#에서 2,6,10,14,18,22 만 뽑아 보세요

In [ ]:
arr_2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
arr_2.shape

(3, 2, 4)

In [ ]:
arr_2[:,:,2]

array([[ 2,  6],
       [10, 14],
       [18, 22]])

In [ ]:
arr_2[:,:,[2]]

array([[[ 2],
        [ 6]],

       [[10],
        [14]],

       [[18],
        [22]]])

In [ ]:
arr_2[:,:,2:3]

array([[[ 2],
        [ 6]],

       [[10],
        [14]],

       [[18],
        [22]]])

In [ ]:
arr_2[:,:,::2]
# 시작:끝:step

array([[[ 0,  2],
        [ 4,  6]],

       [[ 8, 10],
        [12, 14]],

       [[16, 18],
        [20, 22]]])

In [ ]:
arr_1 = np.arange(24)

In [ ]:
arr_1.shape

(24,)

In [ ]:
arr_1_1 = arr_1.reshape(3,2,4) 

In [ ]:
arr_2 = np.arange(72)

In [ ]:
arr_2_1 = arr_2.reshape(9,8)

In [ ]:
arr_2_1.shape

(9, 8)

In [ ]:
arr_2_1.reshape(72)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71])

In [ ]:
arr_2_2 = arr_2_1.reshape(9,2,-1) #-1 을 통해 마지막 값을 저절로 결정하게 해준다. 

In [ ]:
arr_2_2.shape

(9, 2, 4)

In [ ]:
arr_2_1.reshape(9,2)

ValueError: ignored

In [ ]:
arr_2_1.reshape(9,4)

ValueError: ignored

In [ ]:
arr_3= np.arange(24).reshape(2,3,4)
# 6과 18 만을 array에서 뽑아 보세요.

In [ ]:
arr_3[:,[1],[2]]

array([[ 6],
       [18]])

In [ ]:
arr_3.shape

(2, 3, 4)

In [ ]:
arr_3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# 블리언으로 값 선택하기

In [ ]:
names = np.array(["오민엽", "윤상원", "이진경", "김예담", "오민엽","서동한","이해규"])

In [ ]:
names == "오민엽"

array([ True, False, False, False,  True, False, False])

In [ ]:
data = np.random.randn(7,4)

In [ ]:
data

array([[-0.80368151,  0.93356514, -0.32292453, -0.34268275],
       [-0.1844025 ,  0.80583999, -0.61244243, -0.93355433],
       [ 1.79998263, -0.61730889,  0.30287584,  0.88872791],
       [-0.77028317, -1.4703424 ,  0.36013197, -1.04212099],
       [ 0.78712193, -0.08476365, -0.53278676,  2.04434472],
       [-0.8583157 ,  0.29254811, -0.47308548, -0.34605248],
       [ 1.1056219 , -0.58906373,  0.34788192, -0.44085539]])

In [ ]:
data[names == "오민엽"]

array([[-0.80368151,  0.93356514, -0.32292453, -0.34268275],
       [ 0.78712193, -0.08476365, -0.53278676,  2.04434472]])

In [ ]:
bools = names == "오민엽"

In [ ]:
data[bools]

array([[-0.80368151,  0.93356514, -0.32292453, -0.34268275],
       [ 0.78712193, -0.08476365, -0.53278676,  2.04434472]])

In [ ]:
# 질문 data array에서 0 보다 큰수만 추출해 보세요 

In [ ]:
data[data>0]

array([0.93356514, 0.80583999, 1.79998263, 0.30287584, 0.88872791,
       0.36013197, 0.78712193, 2.04434472, 0.29254811, 1.1056219 ,
       0.34788192])

In [ ]:
bools = data > 0 

In [ ]:
data[bools]

array([0.93356514, 0.80583999, 1.79998263, 0.30287584, 0.88872791,
       0.36013197, 0.78712193, 2.04434472, 0.29254811, 1.1056219 ,
       0.34788192])

In [ ]:
# 0보다 작은 숫자들은 0으로 치환 하세요 

In [ ]:
data[data<0] = 0

In [ ]:
data

array([[0.        , 0.93356514, 0.        , 0.        ],
       [0.        , 0.80583999, 0.        , 0.        ],
       [1.79998263, 0.        , 0.30287584, 0.88872791],
       [0.        , 0.        , 0.36013197, 0.        ],
       [0.78712193, 0.        , 0.        , 2.04434472],
       [0.        , 0.29254811, 0.        , 0.        ],
       [1.1056219 , 0.        , 0.34788192, 0.        ]])

In [ ]:
# 팬시색인
# - 정수배열로 색인

In [ ]:
arr = np.random.randn(8,4)

In [ ]:
arr[0] = 0

In [ ]:
arr

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.93935194, -1.99086763, -0.72602363, -0.403365  ],
       [-0.58658175,  0.03144443,  1.45780432,  1.03001252],
       [ 0.54199787,  0.33461012,  0.2152422 ,  0.07107972],
       [-1.77262258,  0.57927814, -0.59396714, -0.70818663],
       [-0.60394579,  0.24090794, -0.23437417, -1.79442097],
       [ 1.37830945,  1.37535811,  0.97456187,  0.4291364 ],
       [-0.95086954, -0.43049474,  1.91525194,  0.99657951]])

In [ ]:
# 특정한 row를 선택하고 싶으면 원하는순서가 명시된 정수가 담긴 list 또는 array를 넘기면 된다.

In [ ]:
arr

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.93935194, -1.99086763, -0.72602363, -0.403365  ],
       [-0.58658175,  0.03144443,  1.45780432,  1.03001252],
       [ 0.54199787,  0.33461012,  0.2152422 ,  0.07107972],
       [-1.77262258,  0.57927814, -0.59396714, -0.70818663],
       [-0.60394579,  0.24090794, -0.23437417, -1.79442097],
       [ 1.37830945,  1.37535811,  0.97456187,  0.4291364 ],
       [-0.95086954, -0.43049474,  1.91525194,  0.99657951]])

In [ ]:
arr[[4,3,0]]

array([[-1.77262258,  0.57927814, -0.59396714, -0.70818663],
       [ 0.54199787,  0.33461012,  0.2152422 ,  0.07107972],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [ ]:
arr = np.arange(32).reshape(8,4)

In [ ]:
arr[:,[1,2]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22],
       [25, 26],
       [29, 30]])

In [ ]:
arr[:,[1,2]][:,1]

array([ 2,  6, 10, 14, 18, 22, 26, 30])

In [ ]:
# 전치와 축변경
# - 배열의 전치는 데이터의 행과 열을 변경 해준다. 

In [ ]:
arr = np.arange(24)

In [ ]:
arr.shape

(24,)

In [ ]:
arr = arr.reshape(3,8)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
arr.T

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [ ]:
arr.transpose()

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [ ]:
arr_1 = np.arange(8)

In [ ]:
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
# 벡터 자체로는 전치 되지 않는다. 
arr_1.T

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr_1.reshape(1,-1)

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [ ]:
arr_1.reshape(1,-1).shape

(1, 8)

In [ ]:
arr_1.reshape(1,-1).T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [ ]:
arr_1.reshape(1,-1).T.shape

(8, 1)

In [ ]:
arr = np.random.randn(5,4)

In [ ]:
# 평균
arr.mean()

0.1484902142190408

In [ ]:
arr.sum()

2.9698042843808157

In [ ]:
# axis = 0 가로 
# axis = 1 세로

In [ ]:
arr.shape

(5, 4)

In [ ]:
arr

array([[-1.13577487,  0.4381739 , -0.1279439 ,  1.21056427],
       [-0.81326855,  0.07864727, -2.34015776,  0.31316436],
       [ 0.42476862,  0.22568741, -0.96123996,  0.70962764],
       [-0.74572584,  2.31825302,  0.5088185 ,  0.29271627],
       [ 0.58354868,  0.61293292,  0.69203099,  0.6849813 ]])

In [ ]:
arr.mean(axis = 0)

array([-0.33729039,  0.7347389 , -0.44569843,  0.64221077])

In [ ]:
arr.mean(axis = 1)

array([ 0.09625485, -0.69040367,  0.09971093,  0.59351549,  0.64337347])

In [ ]:
arr.sum(axis = 0)

array([-1.68645196,  3.67369452, -2.22849213,  3.21105385])

In [ ]:
arr.sum(axis = 1)

array([ 0.3850194 , -2.76161468,  0.39884371,  2.37406196,  2.57349389])

In [ ]:
arr_1 = np.arange(10)

In [ ]:
arr_1.cumsum()

In [ ]:
arr_1 = arr_1.reshape(2,5)

In [ ]:
# arr_1.T.mean(axis = 0)
arr_1.mean(axis = 1)

array([2., 7.])

In [ ]:
arr_1.mean(axis = 0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [ ]:
# 블리언 메소드
# 양수인 원소들의 개수
(arr>0).sum()

14

In [ ]:
# 정렬 
# sort()

In [ ]:
arr_2 = np.random.rand(6)

In [ ]:
arr_2.sort()

In [ ]:
arr_2

array([0.05042024, 0.23558475, 0.40542688, 0.53523076, 0.71897607,
       0.90775773])

In [ ]:
# https://numpy.org/doc/stable/reference/generated/numpy.sort.html
# 내림차순 오름차순 기능은 따로 없다. 
arr_2.sort()

In [ ]:
# 배열 붙이기
# concatenate()
arr_1 = np.array(([11,12,13], [14,15,16]))
arr_2 = np.array(([21,22,23], [24,25,26]))

In [ ]:
# 브로드 캐스팅
np.concatenate([arr_1, arr_2], axis =0)

array([[11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.concatenate([arr_1, arr_2], axis = 1)

array([[11, 12, 13, 21, 22, 23],
       [14, 15, 16, 24, 25, 26]])

In [ ]:
# 브로드 캐스팅
# - 다른모양의 배열간의 산술 연산을 가능해주도록 한다. 

In [ ]:
arr_3 = np.arange(12).reshape(4,3)

In [ ]:
arr_3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr_4 = np.array([1,2,3])

In [ ]:
arr_4.shape

(3,)

In [ ]:
arr_3 + arr_4

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11],
       [10, 12, 14]])

In [ ]:
arr_5 = np.array([[1],[2],[3],[4]])

In [ ]:
arr_3 + arr_5

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])