<a href="https://colab.research.google.com/github/jo-soobin/numpy-pandas/blob/master/01_numpy_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 11.1 자신의 컴퓨터에 numpy을 설치하자. 그리고 NumPy의 버전을 출력해 보자. 밑줄 친 부분에 출력된 내용을 적으시오.



In [ ]:
import numpy as np
np.__version__

'1.21.6'

#### 11.2 크기가 10인 1차원 배열을 생성하여라. 이 배열의 모든 원소는 0 값을 가진다.
##### 1) 0을 10번 입력하여 이 배열 a를 생성하여라. 그리고 이 배열 a를 출력하여라.

In [ ]:
a = np.array([0,0,0,0,0,0,0,0,0,0])

In [ ]:
a.shape

(10,)

##### 2) np.zeros() 함수를 사용하여 배열 b를 생성하여라. 이 배열을 b를 출력하여라.

In [ ]:
b = np.zeros(10)

In [ ]:
b_1 = np.full(10, 0)

In [ ]:
b_1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##### 3) 배열 a와 배열 b의 형을 출력하고 그 결과를 밑줄 친 부분에 적으시오.

In [ ]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


#### 11.3 1에서 10까지 값을 가지는 크기가 10인 1차원 배열 n_arr을 생성하여라. 이 배열이 메모리에서 차지하는 크기는 얼마인가? 다음의 밑줄 친 부분에 알맞은 코드를 입력하여 다음과 같이 바이트 단위로 출력하여라(힌트 : itemsize와 size 속성 값을 곱한다).

In [ ]:
n_arr = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.float64)

In [ ]:
n_arr.itemsize

8

In [ ]:
n_arr.itemsize * n_arr.size

80

In [ ]:
n_arr = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.int32)

In [ ]:
n_arr.itemsize * n_arr.size

40

#### 11.4 1에서 10까지의 정수 값을 가지는 크기가 10인 1차원 배열 a를 arange() 함수를 사용하여 생성하여 출력하여라.
##### 1) 다음과 같이 출력하여라.

In [ ]:
a = np.arange(1,11)

In [ ]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


##### 2) 다음과 같이 역순으로 출력하여라.

In [ ]:
a = a[::-1]
# a[11::-1]

##### 3) 2)의 결과에 reshape()함수를 사용하여, 배열 a를 (2,5) 형태의 다음과 같은 행렬로 변경하여 출력하여라.

In [ ]:
a = a.reshape(2,5)

In [ ]:
print(a)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]


##### 4) 3)의 결과에 reshape()함수를 사용하여, 배열 a를 (5, 2) 형태의 다음과 같은 행렬로 변경하여 출력하여라.

In [ ]:
a = a.reshape(5,2)

In [ ]:
print(a)

[[10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]


#### 11.5 1에서 16까지의 정수값을 가지는 4x4 크기의 배열을 만들어서 다음과 같이 출력하시오. 이 때 arange()와 reshape()을 이용하여 배열을 생성하시오.

In [ ]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 11.6 random.random() 함수를 사용하여 10개의 난수값을 생성하여 다음과 같이 출력하시오. 그리고 이 수들 중에서 최댓값, 최솟값, 평균값을 각각 출력하시오.

In [ ]:
np.random.seed(1) # random 이지만 random seed를 고정하면 random 이 아니라
a = np.random.random(10)

In [ ]:
print(a.max()) #최대
print(a.min()) #최소
print(a.mean()) #평균


0.7203244934421581
0.00011437481734488664
0.3146293077834573


#### 11.7 사용자로부터 2이상의 수 n을 입력으로 받아서, 입력된 수를 바탕으로 다음과 같은 nxn 크기의 다차원 배열 a를 생성하는 프로그램을 작성하시오. 이 때 배열의 내용은 0과 1의 값이 체크 판 패턴으로 교차하여 나타나도록 하여라.

In [ ]:
n = int(input("n : "))
arr_1 = np.full((n,n), 0)
for i in range(n):
  for j in range(n):
    if (i +j) % 2 ==0:
      arr_1[i, j] = 1
print(arr_1)

n : 10
[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]


In [ ]:
arr_1[0,0] = 1

In [ ]:
arr_1

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
arr_1[0,2] = 1

In [ ]:
arr_1

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
arr_1[1,1] = 1

In [ ]:
arr_1

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
n=10
np.arange(1,(n)*(n)+1).reshape(n,n)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#### 11.8 사용자로부터 2이상의 수 n을 입력으로 받아서, 입력된 수를 바탕으로 다음과 같은 대각선 성분의 값이 1에서 n까지 증가하는 다차원 배열 a를 생성하는 프로그램을 작성하시오. 이때 대각선 성분 이외의 값은 모두 0으로 하시오.

In [ ]:
n = int(input("n : "))
arr_1 = np.full((n,n), 0)
for i in range(n):
  for j in range(n):
    if i == j:
      arr_1[i, j] = i+1
print(arr_1)

n : 10
[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]


#### 11.9 사용자로부터 2이상의 수 n을 입력으로 받아서 모든 원소의 값을 1로 가지는 (n, n) shape 행렬 a를 만드시오. 그리고 아래 그림과 같이 이 행렬 a의 경계 값을 제외한 내부의 값을 모두 0으로 가지는 행렬 b를 만드시오(힌트 : np.ones((n, n), dtype='int32')로 모든 원소를 1로 가지는 행렬을 생성한 후 [1:-1, 1:-1] 인덱스를 사용하시오).

In [ ]:
n = int(input("n : "))
a = np.full((n,n), 1)
print(a)
print(id(a))
# b = a.copy()
b = a
b[1: -1, 1:-1] = 0
print(b)
id(b)

n : 10
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
139922422416848
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


139922422416848

#### 11.10 14.9 문제와 달리 a 행렬로부터 경계 값이 모두 0이고 내부가 1인 행렬 c를 다음과 같이 생성하시오. 이때 배열의 슬라이싱을 사용하시오.

In [ ]:
n = int(input("n : "))
a = np.full((n,n), 1)
print(a)
b = a.copy()
# b = a
b[1: -1, 1:-1] = 0
b= (b-1)*(-1)
print(b)
c = a.copy()
c[0, :] = c[-1, :] = c[:, 0] = c[:, -1] = 0

# c[0, :] = 0
# c[-1, :] = 0
# c[:, 0] = 0
# c[:, -1] = 0
print(c)


n : 10
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 11.11 다음과 같은 두 배열 a와 b가 있을 경우 a 배열의 원소내에 b 배열의 원소가 있는지 없는지를 판단하여 출력하는 프로그램을 작성하시오. 이 때 a 배열내의 원소가 b에 있을 경우는 True, 없을 경우는 False를 출력하여라.

In [ ]:
a= np.arange(0,81,10)
b= np.arange(0,21,20)

In [ ]:
bool_arr = np.full(a.shape, False)
indx=0
for i in a:
  if i in b:
    bool_arr[indx] = True
  indx += 1

print(bool_arr)


[ True False  True False False False False False False]


In [ ]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

#### 11.12 임의의 shape으로 이루어진 행렬 x에 대하여 각 성분의 출현 횟수를 구하여 다음과 같이 출력하는 프로그램을 작성하시오.

In [ ]:
arr_1 = np.array([[10,30,40, 50], [10,20,40,50]])
a, b = np.unique(arr_1.flatten(),return_counts=True)

In [ ]:
for i,j in zip(a,b):
  print({i}, {j})

{10} {2}
{20} {1}
{30} {1}
{40} {2}
{50} {2}


#### 11.13 두 배열 a, b가 다음과 같은 원소를 가질때 , 두 배열의 뺄셈을 수행하여 아래와 같이 출력하시오.
##### 1) 집합 연산을 사용하지 말고, for 문과 numpy.append() 메소드를 사용하여 이 문제를 해결 하시오.

In [ ]:
a= np.arange(0,81,10)
b= np.arange(0,21,20)


In [ ]:
np.append?

In [ ]:
c= np.empty(0)
for i in a:
  if i not in b:
    c = np.append(c, i)
print(c)

[10. 30. 40. 50. 60. 70. 80.]


##### 2) numpy.setdiff1d(a, b) 메소드를 사용하여 이 문제를 해결하시오.

In [ ]:
np.setdiff1d(a, b)

array([10, 30, 40, 50, 60, 70, 80])

#### 11.14 다음과 같이 사용자로부터 정수 n을 입력으로 받아서 (n, n) shape의 정방행렬을 만들고 이 행렬의 대각선 성분의 값들이 모두 1로 만드시오(X자 패턴이 되도록 할 것).

In [ ]:
n = int(input('n? : '))
a = np.eye(n, dtype='int32')
b = np.flip(a, axis=1)
c = a + b
if len(c) % 2 == 1:
  c[int(len(c)/2), int(len(c)/2)] = 1
  
print(c)

n? : 10
[[1 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 1]]


#### 11.15 다음과 같이 사용자로부터 정수 n을 입력으로 받아서 (n, n) shape의 정방행렬을 만드시오.
##### 1) 이 행렬의 대각선 성분과 그 아래 값들이 다음과 같이 모두 1이 되도록 만드시오.

In [ ]:
import numpy as np

n = int(input('n : '))
arr_1 = np.full((n, n), 0)

for i in range(n):
  for j in range(n):
    if i >= j:
      arr_1[i, j] = 1
      
print(arr_1)

n : 10
[[1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 1 0 0 0]
 [1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1]]


##### 2) 이 때 모든 행렬의 원소의 합을 다음과 같이 구하시오.

In [ ]:
arr_1.sum()

55

##### 3) 이 행렬의 행 방향 원소의 합을 다음과 같이 구하시오(0축 방향).

In [ ]:
arr_1.sum(axis=0)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

##### 4) 이 행렬의 열 방향 성분의 합을 다음과 같이 구하시오(1축 방향).

In [ ]:
arr_1.sum(axis=1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 11.16 다음과 같은 행렬 a가 있다. 이 행렬 a의 각 성분 값들을 인덱싱하고 concatenate() 함수를 이용하여 b와 같은 형태의 행렬로 만들어라.

In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5], [0, 2, 4], [6, 8, 10]])
a_1 = np.append(a[0], a[2])
a_2 = np.append(a[1], a[3])
b = np.array([a_1, a_2])
print(b)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]]


#### 11.17 다음과 같은 5x5 크기의 2차원 배열 a가 있다. 이 배열을 슬라이싱하여 다음과 같은 배열 b, c, d, e를 완성하여라.

In [ ]:
n = 5
a = np.ones((n, n))
a[0, :] = a[-1, :] = a[:, 0] = a[:, -1] = 0
a[2, 2] = 2
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 2. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 11.18 다음과 같은 2차원 행렬 A, B가 있을 경우 아래 연산이나 행렬식 값를 구하시오.(단, AB는 행렬곱 연산임)

#### 11.19 0에서 23까지의 값을 순서대로 가지는 (4, 3, 2) 형태의 3차원 배열 a가 다음과 같이 있다. 이 배열에 대하여 10번째와 20번째 원소를 구하는 식을 만드시오.
##### 이 식을 이용하여 n과 배열 a를 매개변수로 받아서 원소를 반환하는 get_nth()라는 이름의 함수를 만들고, 10번째와 20번째 배열 원소를 다음과 같이 출력하시오.

#### 11.20 다음과 같은 관계식을 만족시키는 x, y, z를 numpy.linalg.solve() 함수를 이용하여 구하시오.
##### 1) 위 식의 해를 다음과 같이 출력하시오.

##### 2) 선형방정식에서 왼쪽 변의 방정식의 계수는 다음과 같은 행렬로 표기할 수 있다.
##### 이 행렬의 행렬식을 linalg.det() 함수를 사용하여 다음과 같이 구하여라.